"""Initial schema

Revision ID: 060b6b7aa778
Revises: 
Create Date: 2026-09-22 18:34:34.253790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060b6b7aa778'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_model_name'), 'model_registry', ['model_name'], unique=False)
    op.create_table('uav_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tail_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uav_assets_tail_number'), 'uav_assets', ['tail_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('engines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('uav_asset_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uav_asset_id'], ['uav_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engines_serial_number'), 'engines', ['serial_number'], unique=True)
    op.create_table('missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uav_asset_id', sa.UUID(), nullable=False),
    sa.Column('mission_type', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('environmental_profile', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uav_asset_id'], ['uav_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engine_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aux_predictions',
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('engine_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('aux_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_registry.id'], ),
    sa.PrimaryKeyConstraint('ts', 'engine_id')
    )
    op.create_table('bearing_health_readings',
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('engine_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('fault_location', sa.String(), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_registry.id'], ),
    sa.PrimaryKeyConstraint('ts', 'engine_id')
    )
    op.create_table('fault_predictions',
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('engine_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('fault_class', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('probabilities', sa.JSON(), nullable=False),
    sa.CheckConstraint("fault_class IN ('No Failure', 'RC Failure', 'GPS Failure', 'Accelerometer Failure', 'Gyro Failure', 'Compass Failure', 'Barometer Failure')", name='valid_fault_class'),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_registry.id'], ),
    sa.PrimaryKeyConstraint('ts', 'engine_id')
    )
    op.create_table('maintenance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engine_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rul_predictions',
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('engine_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('rul_cycles', sa.Float(), nullable=False),
    sa.Column('degradation_index', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_registry.id'], ),
    sa.PrimaryKeyConstraint('ts', 'engine_id')
    )
    op.create_table('telemetry_readings',
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('engine_id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.Column('rpm', sa.Float(), nullable=False),
    sa.Column('cht', sa.Float(), nullable=False),
    sa.Column('egt', sa.Float(), nullable=False),
    sa.Column('oil_pressure', sa.Float(), nullable=False),
    sa.Column('oil_temp', sa.Float(), nullable=False),
    sa.Column('fuel_flow', sa.Float(), nullable=False),
    sa.Column('vibration_x', sa.Float(), nullable=True),
    sa.Column('vibration_y', sa.Float(), nullable=True),
    sa.Column('vibration_z', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('ts', 'engine_id')
    )
    # ### end Alembic commands ###

    # --- TimescaleDB setup ---
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb;")
    op.execute("SELECT create_hypertable('telemetry_readings', 'ts');")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_readings')
    op.drop_table('rul_predictions')
    op.drop_table('maintenance_logs')
    op.drop_table('fault_predictions')
    op.drop_table('bearing_health_readings')
    op.drop_table('aux_predictions')
    op.drop_table('alerts')
    op.drop_table('missions')
    op.drop_index(op.f('ix_engines_serial_number'), table_name='engines')
    op.drop_table('engines')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_uav_assets_tail_number'), table_name='uav_assets')
    op.drop_table('uav_assets')
    op.drop_index(op.f('ix_model_registry_model_name'), table_name='model_registry')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
